# permissions for end users to view mwservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mwservice-viewer-role
rules:
- apiGroups:
  - mwservice.tomcat.com
  resources:
  - mwservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mwservice.tomcat.com
  resources:
  - mwservices/status
  verbs:
  - get
